<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\Municipios;

class MunicipioSeeder extends Seeder
{

    public function run()
    {
        municipios::create(['nombre' => 'Alto Orinoco', 'id_estado' => '1']);
        municipios::create(['nombre' => 'Atabapo', 'id_estado' => '1']);
        municipios::create(['nombre' => 'Atures', 'id_estado' => '1']);
        municipios::create(['nombre' => 'Autana', 'id_estado' => '1']);
        municipios::create(['nombre' => 'Manapiare', 'id_estado' => '1']);
        municipios::create(['nombre' => 'Maroa', 'id_estado' => '1']);
        municipios::create(['nombre' => 'Río Negro', 'id_estado' => '1']);
        municipios::create(['nombre' => 'Anaco', 'id_estado' => '2']);
        municipios::create(['nombre' => 'Aragua', 'id_estado' => '2']);
        municipios::create(['nombre' => 'Manuel Ezequiel Bruzual', 'id_estado' => '2']);
        municipios::create(['nombre' => 'Diego Bautista Urbaneja', 'id_estado' => '2']);
        municipios::create(['nombre' => 'Fernando Peñalver', 'id_estado' => '2']);
        municipios::create(['nombre' => 'Francisco Del Carmen Carvajal', 'id_estado' => '2']);
        municipios::create(['nombre' => 'General Sir Arthur McGregor', 'id_estado' => '2']);
        municipios::create(['nombre' => 'Guanta', 'id_estado' => '2']);
        municipios::create(['nombre' => 'Independencia', 'id_estado' => '2']);
        municipios::create(['nombre' => 'José Gregorio Monagas', 'id_estado' => '2']);
        municipios::create(['nombre' => 'Juan Antonio Sotillo', 'id_estado' => '2']);
        municipios::create(['nombre' => 'Juan Manuel Cajigal', 'id_estado' => '2']);
        municipios::create(['nombre' => 'Libertad', 'id_estado' => '2']);
        municipios::create(['nombre' => 'Francisco de Miranda', 'id_estado' => '2']);
        municipios::create(['nombre' => 'Pedro María Freites', 'id_estado' => '2']);
        municipios::create(['nombre' => 'Píritu', 'id_estado' => '2']);
        municipios::create(['nombre' => 'San José de Guanipa', 'id_estado' => '2']);
        municipios::create(['nombre' => 'San Juan de Capistrano', 'id_estado' => '2']);
        municipios::create(['nombre' => 'Santa Ana', 'id_estado' => '2']);
        municipios::create(['nombre' => 'Simón Bolívar', 'id_estado' => '2']);
        municipios::create(['nombre' => 'Simón Rodríguez', 'id_estado' => '2']);
        municipios::create(['nombre' => 'Achaguas', 'id_estado' => '3']);
        municipios::create(['nombre' => 'Biruaca', 'id_estado' => '3']);
        municipios::create(['nombre' => 'Muñóz', 'id_estado' => '3']);
        municipios::create(['nombre' => 'Páez', 'id_estado' => '3']);
        municipios::create(['nombre' => 'Pedro Camejo', 'id_estado' => '3']);
        municipios::create(['nombre' => 'Rómulo Gallegos', 'id_estado' => '3']);
        municipios::create(['nombre' => 'San Fernando', 'id_estado' => '3']);
        municipios::create(['nombre' => 'Atanasio Girardot', 'id_estado' => '4']);
        municipios::create(['nombre' => 'Bolívar', 'id_estado' => '4']);
        municipios::create(['nombre' => 'Camatagua', 'id_estado' => '4']);
        municipios::create(['nombre' => 'Francisco Linares Alcántara', 'id_estado' => '4']);
        municipios::create(['nombre' => 'José Ángel Lamas', 'id_estado' => '4']);
        municipios::create(['nombre' => 'José Félix Ribas', 'id_estado' => '4']);
        municipios::create(['nombre' => 'José Rafael Revenga', 'id_estado' => '4']);
        municipios::create(['nombre' => 'Libertador', 'id_estado' => '4']);
        municipios::create(['nombre' => 'Mario Briceño Iragorry', 'id_estado' => '4']);
        municipios::create(['nombre' => 'Ocumare de la Costa de Oro', 'id_estado' => '4']);
        municipios::create(['nombre' => 'San Casimiro', 'id_estado' => '4']);
        municipios::create(['nombre' => 'San Sebastián', 'id_estado' => '4']);
        municipios::create(['nombre' => 'Santiago Mariño', 'id_estado' => '4']);
        municipios::create(['nombre' => 'Santos Michelena', 'id_estado' => '4']);
        municipios::create(['nombre' => 'Sucre', 'id_estado' => '4']);
        municipios::create(['nombre' => 'Tovar', 'id_estado' => '4']);
        municipios::create(['nombre' => 'Urdaneta', 'id_estado' => '4']);
        municipios::create(['nombre' => 'Zamora', 'id_estado' => '4']);
        municipios::create(['nombre' => 'Alberto Arvelo Torrealba', 'id_estado' => '5']);
        municipios::create(['nombre' => 'Andrés Eloy Blanco', 'id_estado' => '5']);
        municipios::create(['nombre' => 'Antonio José de Sucre', 'id_estado' => '5']);
        municipios::create(['nombre' => 'Arismendi', 'id_estado' => '5']);
        municipios::create(['nombre' => 'Barinas', 'id_estado' => '5']);
        municipios::create(['nombre' => 'Bolívar', 'id_estado' => '5']);
        municipios::create(['nombre' => 'Cruz Paredes', 'id_estado' => '5']);
        municipios::create(['nombre' => 'Ezequiel Zamora', 'id_estado' => '5']);
        municipios::create(['nombre' => 'Obispos', 'id_estado' => '5']);
        municipios::create(['nombre' => 'Pedraza', 'id_estado' => '5']);
        municipios::create(['nombre' => 'Rojas', 'id_estado' => '5']);
        municipios::create(['nombre' => 'Sosa', 'id_estado' => '5']);
        municipios::create(['nombre' => 'Caroní', 'id_estado' => '6']);
        municipios::create(['nombre' => 'Cedeño', 'id_estado' => '6']);
        municipios::create(['nombre' => 'El Callao', 'id_estado' => '6']);
        municipios::create(['nombre' => 'Gran Sabana', 'id_estado' => '6']);
        municipios::create(['nombre' => 'Heres', 'id_estado' => '6']);
        municipios::create(['nombre' => 'Piar', 'id_estado' => '6']);
        municipios::create(['nombre' => 'Angostura (Raúl Leoni)', 'id_estado' => '6']);
        municipios::create(['nombre' => 'Roscio', 'id_estado' => '6']);
        municipios::create(['nombre' => 'Sifontes', 'id_estado' => '6']);
        municipios::create(['nombre' => 'Sucre', 'id_estado' => '6']);
        municipios::create(['nombre' => 'Padre Pedro Chien', 'id_estado' => '6']);
        municipios::create(['nombre' => 'Bejuma', 'id_estado' => '7']);
        municipios::create(['nombre' => 'Carlos Arvelo', 'id_estado' => '7']);
        municipios::create(['nombre' => 'Diego Ibarra', 'id_estado' => '7']);
        municipios::create(['nombre' => 'Guacara', 'id_estado' => '7']);
        municipios::create(['nombre' => 'Juan José Mora', 'id_estado' => '7']);
        municipios::create(['nombre' => 'Libertador', 'id_estado' => '7']);
        municipios::create(['nombre' => 'Los Guayos', 'id_estado' => '7']);
        municipios::create(['nombre' => 'Miranda', 'id_estado' => '7']);
        municipios::create(['nombre' => 'Montalbán', 'id_estado' => '7']);
        municipios::create(['nombre' => 'Naguanagua', 'id_estado' => '7']);
        municipios::create(['nombre' => 'Puerto Cabello', 'id_estado' => '7']);
        municipios::create(['nombre' => 'San Diego', 'id_estado' => '7']);
        municipios::create(['nombre' => 'San Joaquín', 'id_estado' => '7']);
        municipios::create(['nombre' => 'Valencia', 'id_estado' => '7']);
        municipios::create(['nombre' => 'Anzoátegui', 'id_estado' => '8']);
        municipios::create(['nombre' => 'Tinaquillo', 'id_estado' => '8']);
        municipios::create(['nombre' => 'Girardot', 'id_estado' => '8']);
        municipios::create(['nombre' => 'Lima Blanco', 'id_estado' => '8']);
        municipios::create(['nombre' => 'Pao de San Juan Bautista', 'id_estado' => '8']);
        municipios::create(['nombre' => 'Ricaurte', 'id_estado' => '8']);
        municipios::create(['nombre' => 'Rómulo Gallegos', 'id_estado' => '8']);
        municipios::create(['nombre' => 'San Carlos', 'id_estado' => '8']);
        municipios::create(['nombre' => 'Tinaco', 'id_estado' => '8']);
        municipios::create(['nombre' => 'Antonio Díaz', 'id_estado' => '9']);
        municipios::create(['nombre' => 'Casacoima', 'id_estado' => '9']);
        municipios::create(['nombre' => 'Pedernales', 'id_estado' => '9']);
        municipios::create(['nombre' => 'Tucupita', 'id_estado' => '9']);
        municipios::create(['nombre' => 'Acosta', 'id_estado' => '10']);
        municipios::create(['nombre' => 'Bolívar', 'id_estado' => '10']);
        municipios::create(['nombre' => 'Buchivacoa', 'id_estado' => '10']);
        municipios::create(['nombre' => 'Cacique Manaure', 'id_estado' => '10']);
        municipios::create(['nombre' => 'Carirubana', 'id_estado' => '10']);
        municipios::create(['nombre' => 'Colina', 'id_estado' => '10']);
        municipios::create(['nombre' => 'Dabajuro', 'id_estado' => '10']);
        municipios::create(['nombre' => 'Democracia', 'id_estado' => '10']);
        municipios::create(['nombre' => 'Falcón', 'id_estado' => '10']);
        municipios::create(['nombre' => 'Federación', 'id_estado' => '10']);
        municipios::create(['nombre' => 'Jacura', 'id_estado' => '10']);
        municipios::create(['nombre' => 'José Laurencio Silva', 'id_estado' => '10']);
        municipios::create(['nombre' => 'Los Taques', 'id_estado' => '10']);
        municipios::create(['nombre' => 'Mauroa', 'id_estado' => '10']);
        municipios::create(['nombre' => 'Miranda', 'id_estado' => '10']);
        municipios::create(['nombre' => 'Monseñor Iturriza', 'id_estado' => '10']);
        municipios::create(['nombre' => 'Palmasola', 'id_estado' => '10']);
        municipios::create(['nombre' => 'Petit', 'id_estado' => '10']);
        municipios::create(['nombre' => 'Píritu', 'id_estado' => '10']);
        municipios::create(['nombre' => 'San Francisco', 'id_estado' => '10']);
        municipios::create(['nombre' => 'Sucre', 'id_estado' => '10']);
        municipios::create(['nombre' => 'Tocópero', 'id_estado' => '10']);
        municipios::create(['nombre' => 'Unión', 'id_estado' => '10']);
        municipios::create(['nombre' => 'Urumaco', 'id_estado' => '10']);
        municipios::create(['nombre' => 'Zamora', 'id_estado' => '10']);
        municipios::create(['nombre' => 'Camaguán', 'id_estado' => '11']);
        municipios::create(['nombre' => 'Chaguaramas', 'id_estado' => '11']);
        municipios::create(['nombre' => 'El Socorro', 'id_estado' => '11']);
        municipios::create(['nombre' => 'José Félix Ribas', 'id_estado' => '11']);
        municipios::create(['nombre' => 'José Tadeo Monagas', 'id_estado' => '11']);
        municipios::create(['nombre' => 'Juan Germán Roscio', 'id_estado' => '11']);
        municipios::create(['nombre' => 'Julián Mellado', 'id_estado' => '11']);
        municipios::create(['nombre' => 'Las Mercedes', 'id_estado' => '11']);
        municipios::create(['nombre' => 'Leonardo Infante', 'id_estado' => '11']);
        municipios::create(['nombre' => 'Pedro Zaraza', 'id_estado' => '11']);
        municipios::create(['nombre' => 'Ortíz', 'id_estado' => '11']);
        municipios::create(['nombre' => 'San Gerónimo de Guayabal', 'id_estado' => '11']);
        municipios::create(['nombre' => 'San José de Guaribe', 'id_estado' => '11']);
        municipios::create(['nombre' => 'Santa María de Ipire', 'id_estado' => '11']);
        municipios::create(['nombre' => 'Sebastián Francisco de Miranda', 'id_estado' => '11']);
        municipios::create(['nombre' => 'Andrés Eloy Blanco', 'id_estado' => '12']);
        municipios::create(['nombre' => 'Crespo', 'id_estado' => '12']);
        municipios::create(['nombre' => 'Iribarren', 'id_estado' => '12']);
        municipios::create(['nombre' => 'Jiménez', 'id_estado' => '12']);
        municipios::create(['nombre' => 'Morán', 'id_estado' => '12']);
        municipios::create(['nombre' => 'Palavecino', 'id_estado' => '12']);
        municipios::create(['nombre' => 'Simón Planas', 'id_estado' => '12']);
        municipios::create(['nombre' => 'Torres', 'id_estado' => '12']);
        municipios::create(['nombre' => 'Urdaneta', 'id_estado' => '12']);
        municipios::create(['nombre' => 'Alberto Adriani', 'id_estado' => '13']);
        municipios::create(['nombre' => 'Andrés Bello', 'id_estado' => '13']);
        municipios::create(['nombre' => 'Antonio Pinto Salinas', 'id_estado' => '13']);
        municipios::create(['nombre' => 'Aricagua', 'id_estado' => '13']);
        municipios::create(['nombre' => 'Arzobispo Chacón', 'id_estado' => '13']);
        municipios::create(['nombre' => 'Campo Elías', 'id_estado' => '13']);
        municipios::create(['nombre' => 'Caracciolo Parra Olmedo', 'id_estado' => '13']);
        municipios::create(['nombre' => 'Cardenal Quintero', 'id_estado' => '13']);
        municipios::create(['nombre' => 'Guaraque', 'id_estado' => '13']);
        municipios::create(['nombre' => 'Julio César Salas', 'id_estado' => '13']);
        municipios::create(['nombre' => 'Justo Briceño', 'id_estado' => '13']);
        municipios::create(['nombre' => 'Libertador', 'id_estado' => '13']);
        municipios::create(['nombre' => 'Miranda', 'id_estado' => '13']);
        municipios::create(['nombre' => 'Obispo Ramos de Lora', 'id_estado' => '13']);
        municipios::create(['nombre' => 'Padre Noguera', 'id_estado' => '13']);
        municipios::create(['nombre' => 'Pueblo Llano', 'id_estado' => '13']);
        municipios::create(['nombre' => 'Rangel', 'id_estado' => '13']);
        municipios::create(['nombre' => 'Rivas Dávila', 'id_estado' => '13']);
        municipios::create(['nombre' => 'Santos Marquina', 'id_estado' => '13']);
        municipios::create(['nombre' => 'Sucre', 'id_estado' => '13']);
        municipios::create(['nombre' => 'Tovar', 'id_estado' => '13']);
        municipios::create(['nombre' => 'Tulio Febres Cordero', 'id_estado' => '13']);
        municipios::create(['nombre' => 'Zea', 'id_estado' => '13']);
        municipios::create(['nombre' => 'Acevedo', 'id_estado' => '14']);
        municipios::create(['nombre' => 'Andrés Bello', 'id_estado' => '14']);
        municipios::create(['nombre' => 'Baruta', 'id_estado' => '14']);
        municipios::create(['nombre' => 'Brión', 'id_estado' => '14']);
        municipios::create(['nombre' => 'Buroz', 'id_estado' => '14']);
        municipios::create(['nombre' => 'Carrizal', 'id_estado' => '14']);
        municipios::create(['nombre' => 'Chacao', 'id_estado' => '14']);
        municipios::create(['nombre' => 'Cristóbal Rojas', 'id_estado' => '14']);
        municipios::create(['nombre' => 'El Hatillo', 'id_estado' => '14']);
        municipios::create(['nombre' => 'Guaicaipuro', 'id_estado' => '14']);
        municipios::create(['nombre' => 'Independencia', 'id_estado' => '14']);
        municipios::create(['nombre' => 'Lander', 'id_estado' => '14']);
        municipios::create(['nombre' => 'Los Salias', 'id_estado' => '14']);
        municipios::create(['nombre' => 'Páez', 'id_estado' => '14']);
        municipios::create(['nombre' => 'Paz Castillo', 'id_estado' => '14']);
        municipios::create(['nombre' => 'Pedro Gual', 'id_estado' => '14']);
        municipios::create(['nombre' => 'Plaza', 'id_estado' => '14']);
        municipios::create(['nombre' => 'Simón Bolívar', 'id_estado' => '14']);
        municipios::create(['nombre' => 'Sucre', 'id_estado' => '14']);
        municipios::create(['nombre' => 'Urdaneta', 'id_estado' => '14']);
        municipios::create(['nombre' => 'Zamora', 'id_estado' => '14']);
        municipios::create(['nombre' => 'Acosta', 'id_estado' => '15']);
        municipios::create(['nombre' => 'Aguasay', 'id_estado' => '15']);
        municipios::create(['nombre' => 'Bolívar', 'id_estado' => '15']);
        municipios::create(['nombre' => 'Caripe', 'id_estado' => '15']);
        municipios::create(['nombre' => 'Cedeño', 'id_estado' => '15']);
        municipios::create(['nombre' => 'Ezequiel Zamora', 'id_estado' => '15']);
        municipios::create(['nombre' => 'Libertador', 'id_estado' => '15']);
        municipios::create(['nombre' => 'Maturín', 'id_estado' => '15']);
        municipios::create(['nombre' => 'Piar', 'id_estado' => '15']);
        municipios::create(['nombre' => 'Punceres', 'id_estado' => '15']);
        municipios::create(['nombre' => 'Santa Bárbara', 'id_estado' => '15']);
        municipios::create(['nombre' => 'Sotillo', 'id_estado' => '15']);
        municipios::create(['nombre' => 'Uracoa', 'id_estado' => '15']);
        municipios::create(['nombre' => 'Antolín del Campo', 'id_estado' => '16']);
        municipios::create(['nombre' => 'Arismendi', 'id_estado' => '16']);
        municipios::create(['nombre' => 'García', 'id_estado' => '16']);
        municipios::create(['nombre' => 'Gómez', 'id_estado' => '16']);
        municipios::create(['nombre' => 'Maneiro', 'id_estado' => '16']);
        municipios::create(['nombre' => 'Marcano', 'id_estado' => '16']);
        municipios::create(['nombre' => 'Mariño', 'id_estado' => '16']);
        municipios::create(['nombre' => 'Península de Macanao', 'id_estado' => '16']);
        municipios::create(['nombre' => 'Tubores', 'id_estado' => '16']);
        municipios::create(['nombre' => 'Villalba', 'id_estado' => '16']);
        municipios::create(['nombre' => 'Díaz', 'id_estado' => '16']);
        municipios::create(['nombre' => 'Agua Blanca', 'id_estado' => '17']);
        municipios::create(['nombre' => 'Araure', 'id_estado' => '17']);
        municipios::create(['nombre' => 'Esteller', 'id_estado' => '17']);
        municipios::create(['nombre' => 'Guanare', 'id_estado' => '17']);
        municipios::create(['nombre' => 'Guanarito', 'id_estado' => '17']);
        municipios::create(['nombre' => 'Monseñor José Vicente de Unda', 'id_estado' => '17']);
        municipios::create(['nombre' => 'Ospino', 'id_estado' => '17']);
        municipios::create(['nombre' => 'Páez', 'id_estado' => '17']);
        municipios::create(['nombre' => 'Papelón', 'id_estado' => '17']);
        municipios::create(['nombre' => 'San Genaro de Boconoíto', 'id_estado' => '17']);
        municipios::create(['nombre' => 'San Rafael de Onoto', 'id_estado' => '17']);
        municipios::create(['nombre' => 'Santa Rosalía', 'id_estado' => '17']);
        municipios::create(['nombre' => 'Sucre', 'id_estado' => '17']);
        municipios::create(['nombre' => 'Turén', 'id_estado' => '17']);
        municipios::create(['nombre' => 'Andrés Eloy Blanco', 'id_estado' => '18']);
        municipios::create(['nombre' => 'Andrés Mata', 'id_estado' => '18']);
        municipios::create(['nombre' => 'Arismendi', 'id_estado' => '18']);
        municipios::create(['nombre' => 'Benítez', 'id_estado' => '18']);
        municipios::create(['nombre' => 'Bermúdez', 'id_estado' => '18']);
        municipios::create(['nombre' => 'Bolívar', 'id_estado' => '18']);
        municipios::create(['nombre' => 'Cajigal', 'id_estado' => '18']);
        municipios::create(['nombre' => 'Cruz Salmerón Acosta', 'id_estado' => '18']);
        municipios::create(['nombre' => 'Libertador', 'id_estado' => '18']);
        municipios::create(['nombre' => 'Mariño', 'id_estado' => '18']);
        municipios::create(['nombre' => 'Mejía', 'id_estado' => '18']);
        municipios::create(['nombre' => 'Montes', 'id_estado' => '18']);
        municipios::create(['nombre' => 'Ribero', 'id_estado' => '18']);
        municipios::create(['nombre' => 'Sucre', 'id_estado' => '18']);
        municipios::create(['nombre' => 'Valdéz', 'id_estado' => '18']);
        municipios::create(['nombre' => 'Andrés Bello', 'id_estado' => '19']);
        municipios::create(['nombre' => 'Antonio Rómulo Costa', 'id_estado' => '19']);
        municipios::create(['nombre' => 'Ayacucho', 'id_estado' => '19']);
        municipios::create(['nombre' => 'Bolívar', 'id_estado' => '19']);
        municipios::create(['nombre' => 'Cárdenas', 'id_estado' => '19']);
        municipios::create(['nombre' => 'Córdoba', 'id_estado' => '19']);
        municipios::create(['nombre' => 'Fernández Feo', 'id_estado' => '19']);
        municipios::create(['nombre' => 'Francisco de Miranda', 'id_estado' => '19']);
        municipios::create(['nombre' => 'García de Hevia', 'id_estado' => '19']);
        municipios::create(['nombre' => 'Guásimos', 'id_estado' => '19']);
        municipios::create(['nombre' => 'Independencia', 'id_estado' => '19']);
        municipios::create(['nombre' => 'Jáuregui', 'id_estado' => '19']);
        municipios::create(['nombre' => 'José María Vargas', 'id_estado' => '19']);
        municipios::create(['nombre' => 'Junín', 'id_estado' => '19']);
        municipios::create(['nombre' => 'Libertad', 'id_estado' => '19']);
        municipios::create(['nombre' => 'Libertador', 'id_estado' => '19']);
        municipios::create(['nombre' => 'Lobatera', 'id_estado' => '19']);
        municipios::create(['nombre' => 'Michelena', 'id_estado' => '19']);
        municipios::create(['nombre' => 'Panamericano', 'id_estado' => '19']);
        municipios::create(['nombre' => 'Pedro María Ureña', 'id_estado' => '19']);
        municipios::create(['nombre' => 'Rafael Urdaneta', 'id_estado' => '19']);
        municipios::create(['nombre' => 'Samuel Darío Maldonado', 'id_estado' => '19']);
        municipios::create(['nombre' => 'San Cristóbal', 'id_estado' => '19']);
        municipios::create(['nombre' => 'Seboruco', 'id_estado' => '19']);
        municipios::create(['nombre' => 'Simón Rodríguez', 'id_estado' => '19']);
        municipios::create(['nombre' => 'Sucre', 'id_estado' => '19']);
        municipios::create(['nombre' => 'Torbes', 'id_estado' => '19']);
        municipios::create(['nombre' => 'Uribante', 'id_estado' => '19']);
        municipios::create(['nombre' => 'San Judas Tadeo', 'id_estado' => '19']);
        municipios::create(['nombre' => 'Andrés Bello', 'id_estado' => '20']);
        municipios::create(['nombre' => 'Boconó', 'id_estado' => '20']);
        municipios::create(['nombre' => 'Bolívar', 'id_estado' => '20']);
        municipios::create(['nombre' => 'Candelaria', 'id_estado' => '20']);
        municipios::create(['nombre' => 'Carache', 'id_estado' => '20']);
        municipios::create(['nombre' => 'Escuque', 'id_estado' => '20']);
        municipios::create(['nombre' => 'José Felipe Márquez Cañizalez', 'id_estado' => '20']);
        municipios::create(['nombre' => 'Juan Vicente Campos Elías', 'id_estado' => '20']);
        municipios::create(['nombre' => 'La Ceiba', 'id_estado' => '20']);
        municipios::create(['nombre' => 'Miranda', 'id_estado' => '20']);
        municipios::create(['nombre' => 'Monte Carmelo', 'id_estado' => '20']);
        municipios::create(['nombre' => 'Motatán', 'id_estado' => '20']);
        municipios::create(['nombre' => 'Pampán', 'id_estado' => '20']);
        municipios::create(['nombre' => 'Pampanito', 'id_estado' => '20']);
        municipios::create(['nombre' => 'Rafael Rangel', 'id_estado' => '20']);
        municipios::create(['nombre' => 'San Rafael de Carvajal', 'id_estado' => '20']);
        municipios::create(['nombre' => 'Sucre', 'id_estado' => '20']);
        municipios::create(['nombre' => 'Trujillo', 'id_estado' => '20']);
        municipios::create(['nombre' => 'Urdaneta', 'id_estado' => '20']);
        municipios::create(['nombre' => 'Valera', 'id_estado' => '20']);
        municipios::create(['nombre' => 'Vargas', 'id_estado' => '21']);
        municipios::create(['nombre' => 'Arístides Bastidas', 'id_estado' => '22']);
        municipios::create(['nombre' => 'Bolívar', 'id_estado' => '22']);
        municipios::create(['nombre' => 'Bruzual', 'id_estado' => '22']);
        municipios::create(['nombre' => 'Cocorote', 'id_estado' => '22']);
        municipios::create(['nombre' => 'Independencia', 'id_estado' => '22']);
        municipios::create(['nombre' => 'José Antonio Páez', 'id_estado' => '22']);
        municipios::create(['nombre' => 'La Trinidad', 'id_estado' => '22']);
        municipios::create(['nombre' => 'Manuel Monge', 'id_estado' => '22']);
        municipios::create(['nombre' => 'Nirgua', 'id_estado' => '22']);
        municipios::create(['nombre' => 'Peña', 'id_estado' => '22']);
        municipios::create(['nombre' => 'San Felipe', 'id_estado' => '22']);
        municipios::create(['nombre' => 'Sucre', 'id_estado' => '22']);
        municipios::create(['nombre' => 'Urachiche', 'id_estado' => '22']);
        municipios::create(['nombre' => 'José Joaquín Veroes', 'id_estado' => '22']);
        municipios::create(['nombre' => 'Almirante Padilla', 'id_estado' => '23']);
        municipios::create(['nombre' => 'Baralt', 'id_estado' => '23']);
        municipios::create(['nombre' => 'Cabimas', 'id_estado' => '23']);
        municipios::create(['nombre' => 'Catatumbo', 'id_estado' => '23']);
        municipios::create(['nombre' => 'Colón', 'id_estado' => '23']);
        municipios::create(['nombre' => 'Francisco Javier Pulgar', 'id_estado' => '23']);
        municipios::create(['nombre' => 'Páez', 'id_estado' => '23']);
        municipios::create(['nombre' => 'Jesús Enrique Losada', 'id_estado' => '23']);
        municipios::create(['nombre' => 'Jesús María Semprún', 'id_estado' => '23']);
        municipios::create(['nombre' => 'La Cañada de Urdaneta', 'id_estado' => '23']);
        municipios::create(['nombre' => 'Lagunillas', 'id_estado' => '23']);
        municipios::create(['nombre' => 'Machiques de Perijá', 'id_estado' => '23']);
        municipios::create(['nombre' => 'Mara', 'id_estado' => '23']);
        municipios::create(['nombre' => 'Maracaibo', 'id_estado' => '23']);
        municipios::create(['nombre' => 'Miranda', 'id_estado' => '23']);
        municipios::create(['nombre' => 'Rosario de Perijá', 'id_estado' => '23']);
        municipios::create(['nombre' => 'San Francisco', 'id_estado' => '23']);
        municipios::create(['nombre' => 'Santa Rita', 'id_estado' => '23']);
        municipios::create(['nombre' => 'Simón Bolívar', 'id_estado' => '23']);
        municipios::create(['nombre' => 'Sucre', 'id_estado' => '23']);
        municipios::create(['nombre' => 'Valmore Rodríguez', 'id_estado' => '23']);
        municipios::create(['nombre' => 'Libertador', 'id_estado' => '24']);
    }
}
